import { defineConfig } from 'vite'
import path             from 'path'
import tailwindcss      from '@tailwindcss/vite'
import vue              from '@vitejs/plugin-vue'


// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  
  /* This block forwards browser requests to http://localhost:8000 */
  /*  This enables browser requests on http://localhost:5173 */
  /*  This was generated by GPT-5 mini and may be fragile */
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
        secure: false,
      }
    }
  },
  /* */

})
