#!/bin/sh
set -e

mkdir -p /rsync /rsync/ssh_host_keys

# Generate persistent host keys on first start.
if [ ! -f /rsync/ssh_host_keys/ssh_host_ed25519_key ]; then
    ssh-keygen -q -t ed25519 -N '' -f /rsync/ssh_host_keys/ssh_host_ed25519_key
fi
if [ ! -f /rsync/ssh_host_keys/ssh_host_rsa_key ]; then
    ssh-keygen -q -t rsa -b 4096 -N '' -f /rsync/ssh_host_keys/ssh_host_rsa_key
fi
chmod 0600 /rsync/ssh_host_keys/ssh_host_*_key

# authorized_keys is regenerated by the Django container on every token
# change. Ensure the file exists so sshd can start even before the first
# key is registered.
if [ ! -f /rsync/authorized_keys ]; then
    touch /rsync/authorized_keys
fi
chmod 0600 /rsync/authorized_keys

# sshd strips the environment for each session, so the forced-command
# wrapper can't see DJANGO_SECRET_KEY, POSTGRES_*, etc. Dump the container's
# env (loaded by docker-compose's env_file) to a file the wrapper reads at
# startup. NUL-delimited so values containing newlines survive.
env -0 > /etc/xrb-rsync.env
chmod 0600 /etc/xrb-rsync.env

exec /usr/sbin/sshd -D -e
